db:
        image: oracle-database:19.3.0-SE
        restart: always
        environment:
                ORACLE_SID: ORCLCDB
                ORACLE_PDB: ORCLPDB1
                ORACLE_PWD: programaciondaw
        ports:
                - "1521:1521"
                - "5500:5500"
                  #        volumes:
                #- "./.docker/mysql/conf.d:/etc/mysql/conf.d"
                #Directorio Scripts de inicializacion
                #- "./.docker/initbd:/docker-entrypoint-initdb.d/setup"

