db:
        image: oracle-database:18.4.0-XE
        restart: always
        environment:
                #El SID es 'XE' y no se puede cambiar
                ORACLE_PWD: programaciondaw
        ports:
                - "1521:1521"
                - "5505:5500"
                  #        volumes:
                #- "./.docker/mysql/conf.d:/etc/mysql/conf.d"
                #Directorio Scripts de inicializacion
                #- "./.docker/initbd:/docker-entrypoint-initdb.d/setup"

