db:
        image: oracle-database:11.2.0-XE
        restart: always
        mem_limit: 2g
        shm_size: 1g
        environment:
                #El SID es 'XE' y no se puede cambiar
                ORACLE_PWD: programaciondaw
        ports:
                - "1521:1521"
                - "8080:8080"
                  #        volumes:
                #- "./.docker/mysql/conf.d:/etc/mysql/conf.d"
                #Directorio Scripts de inicializacion
                #- "./.docker/initbd:/docker-entrypoint-initdb.d/setup"

